server:
    port: 8081
spring:
    application.name: testMCPServer
ai:
    mcp:
        server:
            stdio: false
            enabled: true
            type: SYNC
            name: zoo-mcp-server
            version: 1.0.0
            capabilities:
                tool: true
                resource: false
                prompt: false
                completion: false
